disabled = false
locale = "id"
label = "Bahasa Indonesia"
weight = 2
title = "Azriel Fidzlie"


[params]
  displayName = "Indonesia"
  isoCode = "id"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "images/logo.png"
  secondaryLogo = "images/secondary-logo.png"
  copyright = "© { year } Azriel Fidzlie. All rights reserved."

[params.author]
  name = "Azriel Fidzlie, S.Kom"
  headline = "Selalu Belajar Hal Baru"
  image = "images/authors/azriel.jpg"
  imageQuality = 96
  bio = "Selalu Belajar Hal Baru"
  links = [
    { facebook = "https://facebook.com/ulee.undead" },
    { twitter = "https://twitter.com/0zunu_" },
    { instagram = "https://instagram.com/mas.ulee" },
    { youtube = "https://www.youtube.com/@O_zunu/" },
    { github = "https://github.com/0zunu" },
    { linkedin = "https://www.linkedin.com/in/azriel-fidzlie" },
    { email = "mailto:fidzlieazriel@gmail.com" },
  ]